networks:
  default:
    name: myanibot 
volumes:
  redis_data:
services:
  redis:
    image: 'redis:latest'
    restart: unless-stopped
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

  bot:
    build: ./bot
    env_file:
      - ./bot/.env
    depends_on:
      - redis
    restart: on-failure

  web1:
    build: ./web-server
    hostname: myanibot.auth1
    ports:
      - '3001:3000'
    env_file:
      - ./web-server/.env
    depends_on:
      - redis
    restart: on-failure
    
  web2:
    build: ./web-server
    hostname: myanibot.auth2
    ports:
      - '3002:3000'
    env_file:
      - ./web-server/.env
    depends_on:
      - redis
    restart: on-failure

  nginx:
    image: nginx
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/certs
    depends_on:
      - web1
      - web2
    restart: always

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
